#!/usr/bin/env python
from notmuch import Query, Database
# dangerous expunge command: expunge tag:deleted

# explanation: in gmail; "visible IMAP Folders" can be configured;  in
# https://mail.google.com/mail/u/0/#settings/labels
# my case I configured "INBOX", "Sent" and "Drafts" to be visible to
# IMAP clients.

# https://mail.google.com/mail/u/0/#settings/fwdandpop
# Then, in the POP/IMAP settings; choose these two options
# When I mark a message in IMAP as deleted: Auto-Expunge off - Wait for the client to update the server.
# When a message is marked as deleted and expunged from the last visible IMAP folder: Move the message to the Trash



# mails expunged locally will be moved to Trash by gmail and permanently deleted 30days later
# 

db = Database('/home/yc/Mail', mode=Database.MODE.READ_WRITE)
import pathlib
def rm_deleted():
    msgs = Query(db, "tag:deleted").search_messages()
    msgs_list = list(msgs)
    for msg in msgs_list:
        path_msg = msg.get_filename()
        pathlib.Path(path_msg).unlink(missing_ok=True)
        db.remove_message(path_msg)
    return 0
# notmuch search --output=files --format=text0 tag:deleted | xargs --no-run-if-empty -r0 rm -f

if __name__ == "__main__":
    rm_deleted()
