icons_format = "{icon}"

[theme]
theme = "solarized-dark"

[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "none"

[[block]]
block = "hueshift"
hue_shifter = "wl_gammarelay_rs"
step = 50
click_temp = 3500

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "
interval = 1

[[block]]
block = "backlight"
device = "intel_backlight"
missing_format = ""

[[block]]
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "net"
format = " $icon {$signal_strength |Wired } "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
